import type { Metadata } from 'next'
import { Livvic } from 'next/font/google'
import './globals.css'
import { NavMenu } from '@/components/nav-menu'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
const livvic = Livvic({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
    title: 'Sandcibatta App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="es" translate="no">
            <body className={livvic.className}>
                <header>
                    <NavMenu />
                </header>
                {children}
                <ToastContainer position="bottom-left" />
            </body>
        </html>
    )
}
